#ifndef LVOX3_READER_ASCIIGRID3D_DEF_MODELS_H
#define LVOX3_READER_ASCIIGRID3D_DEF_MODELS_H

/**
  * DEFINITION OF MODELS USED BY THE ASCII GRID 3D READER LVOX3
  */

#define DEF_LVOX3_Reader_ASCIIGRD3D_grid3DOut     "grid"

#endif // LVOX3_READER_ASCIIGRID3D_DEF_MODELS_H
