name: build
on: [workflow_dispatch]

jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            configurePreset: 'windows-standalone'
          - os: ubuntu-latest
            configurePreset: 'linux-standalone'
    steps:
      - uses: actions/checkout@v4
        with:
            submodules: true

      - uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        if: runner.os == 'Windows'
        uses: lukka/run-vcpkg@v11
        id: runvcpkg
        with:
            vcpkgGitCommitId: '120deac3062162151622ca4860575a33844ba10b' # 2025.08.27
            vcpkgJsonGlob: "vcpkg.json"
            runVcpkgInstall: true

      - name: Linux setup PPA for pdal
        if: runner.os == 'Linux'
        run: |
          sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update

      - name: Install Linux dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        if: runner.os == 'Linux'
        with:
          packages: libpdal-dev libhdf5-dev libeigen3-dev libgtest-dev libbenchmark-dev
          version: 1.0


      - name: CMake generate project
        uses: lukka/run-cmake@v10
        with:
          configurePreset: '${{ matrix.configurePreset }}'

      - name: Build
        run: cmake --build ${{github.workspace}}/build
