name: ci-standalone
on:
  workflow_call:
    inputs:
      do_release:
        required: false
        type: boolean
        default: false
      do_testing:
        required: false
        type: boolean
        default: false

jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows-release
            configurePreset: 'windows-standalone'
          - os: ubuntu-latest
            configurePreset: 'linux-standalone'
    steps:
      - uses: actions/checkout@v4

      - name: Install Conan
        uses: conan-io/setup-conan@v1
        with:
          cache_packages: true

      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.30.0"

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v3
        if: runner.os == 'Windows'

      - name: Install Conan dependencies
        run: |
          conan install . --build=missing  --output-folder=build  -s compiler.cppstd=20
          conan cache clean

      - name: Configure project
        run: cmake --preset standalone-conan-dev -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build
