name: Standalone build and test
on:
  push:
    branches: [main]
  pull_request:

jobs:
  call-build:
    uses: ./.github/workflows/ci-standalone.yml
    with:
      do_release: false
      do_testing: true
